### ISSUE TITLE
Bidra til altinndesign på data.altinn.no

### ISSUE THREAD

**Issue by anettepettersen** [Altinn/portal#4]
Få hjelp av Lene?
Kan gjøre noen endringer, men er mye bundet av templates (Bjøn)

Dagens:
<img width="673" alt="image" src="https://user-images.githubusercontent.com/1464915/168024522-b8948d84-81fb-49f6-a675-b9332764c77c.png">

**Comment by hannefinnoy** [comment]
Skulle ikke @mrosvik ta en titt på dette i høst?

**Comment by mrosvik** [comment]
Beklager @hannefinnoy, det har gått helt i glemmeboken! (evt. druknet i andre ting som brenner) 😅
Jeg sender Erlend en melding nå for tilgang 😊

**Comment by mrosvik** [comment]
Det ligger bare i test foreløpig. Må få det ut i prod.. Og kanskje prøve å gjøre ytterlige justeringer på knappene...

![image](https://user-images.githubusercontent.com/1464915/159035095-3bbb9733-44c1-4426-9d04-72a971429660.png) 

Har måtte prioritert litt andre ting, men kan se på det igjen neste uke og forhåpentligvis få det ut i prod.

**Comment by mrosvik** [comment]
Det ligger i prod nå [data.altinn.no ](https://data.altinn.no/)
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/1464915/168024141-b5fc3be5-62e4-465f-aeae-a89454971ca1.png">
